# vim: set ts=2 sts=2 sw=2 expandtab :
dist: xenial
sudo: required
language: bash
services:
  - docker

before_install:
  - sudo apt-get install -y python3-pip python3-setuptools
  - sudo pip3 install --upgrade pip
  - sudo pip install PyGithub
  - curl -Ls -o docker-build https://github.com/mate-desktop/mate-dev-scripts/raw/master/travis/docker-build
  - chmod +x docker-build

install:
  - ./docker-build --name ${DISTRO} --config .travis.yml --install

script:
  - ./docker-build --name ${DISTRO} --verbose --config .travis.yml --build meson

deploy:
  provider: script
  script: ./docker-build --name ${DISTRO} --verbose --config .travis.yml --release
  skip_cleanup: true
  on:
    tags: true
    condition: "$TRAVIS_TAG =~ ^v.*$ && $DISTRO == fedora:rawhide"

env:
  - DISTRO="archlinux/base"
  - DISTRO="debian:sid"
  - DISTRO="fedora:rawhide"
  - DISTRO="ubuntu:19.04"

##########################################################
# THE FOLLOWING LINES IS USED BY docker-build
##########################################################
requires:
  archlinux:
    - gettext
    - git
    - gobject-introspection
    - gtk3
    - meson
    - vala

  debian:
    - git
    - gobject-introspection
    - gtk-doc-tools
    - intltool
    - libgirepository1.0-dev
    - libglib2.0-dev
    - libglib2.0-dev
    - libgtk-3-dev
    - libx11-dev
    - meson
    - valac

  fedora:
    - gcc
    - gettext
    - git
    - gobject-introspection-devel
    - gtk-doc
    - gtk3-devel
    - meson
    - ninja-build
    - redhat-rpm-config
    - vala
    - vala-devel

  ubuntu:
    - git
    - gobject-introspection
    - gtk-doc-tools
    - intltool
    - libgirepository1.0-dev
    - libglib2.0-dev
    - libgtk-3-dev
    - libglib2.0-dev
    - libx11-dev
    - meson
    - valac

variables:
  - CFLAGS="-Wall -Werror=format-security"

# Remove the comment if you need special parameters
configures:
  meson:
    - --prefix /usr
    - -Denable_gtk_doc=true
    - -Dwith_introspection=true
    - -Dwith_vala=true
    - -Denable_tests=true

# Remove the comment if you need some thing do before build.
before_scripts:
  - cd ${START_DIR}
  - git clone --depth 1 https://github.com/yetist/lunar-date.git lunar-date-build
  - cd lunar-date-build
  - if [ -d _build ]; then
  -     rm -rf _build
  - fi
  - meson _build --prefix /usr -Denable_gtk_doc=true -Dwith_introspection=true -Dwith_vala=true -Denable_tests=true
  - ninja -C _build
  - ninja -C _build install

after_scripts:
  - cd ${BUILD_DIR}
  - ninja dist

releases:
  draft: False
  prerelease: False
  checksum: False
  base_version: 3.0.0
  file_glob: True
  files: _build/meson-dist/lunar-calendar-*.tar.xz*
